### ISSUE TITLE
error running finance-bomse and finance_yson

### ISSUE THREAD

**Issue by dr-rakesh-sarwal** [abhijit86k/finance-bomse#1]
rs@debian:~/Documents$ gnc-fq-dump yahoo_json SBIN.NS
Finance::Quote fields Gnucash uses:
    symbol: SBIN.NS              <=== required
      date: ** missing **        <=== recommended
  currency: ** missing **        <=== required
      last:                      <=\       
       nav:                      <=== one of these
     price:                      <=/        
  timezone:                      <=== optional

** This stock quote cannot be used by GnuCash!
===============
As can be seen, I have the  pm in right place, Quote.pm edited. Both BOMSE and yahoo_json do not work.
Am I missing something basic ? Mumbaistock.pm works on my system.
I am pursuing this with a request to generate quote for debt instruments on BSE from http://www.bseindia.com/markets/equity/EQReports/BhavCopyDebt.aspx?expandable=3

**Comment by abhijit86k** [comment]
Yahoo Finance has changed something and possibly permanently deactivated JSON Quotes. I can't do anything to fix this at the moment. I'm working on an alternative - will push it later this week if I get time.

**Comment by abhijit86k** [comment]
@sarwalr Changes pushed to master.
