### ISSUE TITLE
Error Running BOMSE.pm

### ISSUE THREAD

**Issue by dr-rakesh-sarwal** [abhijit86k/finance-bomse#2]
Hi,

Followed instructions, getting bomse on gnc-fq-check, but error on Debian 9.0. Please correct me if there is something basic that I am missing:
======================
rs@debian:/media/rs/backup/Reserve/1-finances/gnucash/bomse$ ./nsetoolsfetch.py INDIGO
Traceback (most recent call last):
  File "./nsetoolsfetch.py", line 26, in <module>
    from nsetools import Nse
ImportError: No module named nsetools
========================================
Traceback (most recent call last):
  File "./nsetoolsfetch.py", line 26, in <module>
    from nsetools import Nse
ImportError: No module named nsetools
Uncaught exception from user code:
	malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/share/perl5/Finance/Quote/BOMSE.pm line 65.
	Finance::Quote::BOMSE::bomse(Finance::Quote=HASH(0x55a0764c8c90), "SBIN") called at /usr/share/perl5/Finance/Quote.pm line 579
	Finance::Quote::fetch(Finance::Quote=HASH(0x55a0764c8c90), "bomse", "SBIN") called at /usr/bin/gnc-fq-dump line 180
===================================
rs

**Comment by abhijit86k** [comment]
The error message has a hint to the problem:
```
from nsetools import Nse
ImportError: No module named nsetools
```
You need to install the nsetools module.
If you have pip you can run:
`sudo pip install nsetools`
Otherwise you will have to figure out which package to install using synaptic.

**Comment by abhijit86k** [comment]
Updated the code with cleanup and fixes. Everything should be working now.
